Adding linting checks with mypy.
Integrating with pytest.

Updating types.

updating siginature of order_tracks_by_file_id to raise ValueError if KeyError is raised to ensure the contract of track.file_id when a None value is assigned is preserved.

updating tests.yml to specify ubuntu version as the ubuntu-latest
[label](https://github.com/actions/runner-images/pull/10807)
changing affects which version of the mkvtoolnix
[repo](https://mkvtoolnix.download/downloads.html#ubuntu) to download from.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,25 +1,23 @@
 name: Tests
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 on: [push, pull_request]
 jobs:
   run:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     steps:
       - name: Check out repository
         uses: actions/checkout@v4
-      - name: Set up python
-        id: setup-python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.11'
       - name: Set up MKVToolNix repository
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wget gnupg
+          sudo apt-get -qq update
+          sudo apt-get -qq install -y wget gnupg
           sudo wget -O /usr/share/keyrings/gpg-pub-moritzbunkus.gpg https://mkvtoolnix.download/gpg-pub-moritzbunkus.gpg
           echo "deb [arch=amd64 signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/mkvtoolnix.list
-          sudo apt-get update
+          sudo apt-get -qq update
       - name: Install MKVToolNix
-        run: sudo apt-get install -y mkvtoolnix mkvtoolnix-gui
+        run: sudo apt-get -qq install -y mkvtoolnix mkvtoolnix-gui
       - name: Verify MKVToolNix installation
         run: mkvmerge -V
       - name: Install Poetry
@@ -29,7 +27,26 @@ jobs:
           virtualenvs-create: true
           virtualenvs-in-project: true
           installer-parallel: true
+      - name: Set up Python
+        id: setup-python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+      - name: Install Poetry
+        uses: snok/install-poetry@v1
+        with:
+          version: 1.8.3
+          virtualenvs-create: true
+          virtualenvs-in-project: true
+          installer-parallel: true
+      - name: Load cached venv
+        id: cached-poetry-dependencies
+        uses: actions/cache@v4
+        with:
+          path: .venv
+          key: venv-pypi-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
       - name: Install dependencies
+        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
         run: poetry install --no-interaction --no-root
       - name: Install project
         run: poetry install --no-interaction
@@ -46,3 +63,8 @@ jobs:
           verbose: true
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './test-results/junit.xml'
